### ISSUE TITLE
Mistake in bban_format dict?

### ISSUE THREAD

**Issue by dermorz** [berend/pyiban#2]
```
bban_format ={
    "AD": {
        "composition": "{04:bank_code}{04:branch_code}{012:account_number}",
        "country": "Andorra",
        "bank_code"
        "length": 24
    },
    …
```

evaluates to

```
bban_format ={
    "AD": {
        "composition": "{04:bank_code}{04:branch_code}{012:account_number}",
        "country": "Andorra",
        "bank_codelength": 24
    },
    …
```

Note the `bank_codelength`. This does not seem intended and is well hidden, because strings with the same indent level just get appended and don't throw an error like "no value for this key".

**Comment by berend** [comment]
Yes, that is an error. The complete bban_format is basically just a placeholder tight now. There is a lot of data missing. I am going to write a parser, that generates to format string from an official source
