### ISSUE TITLE
Renaming proposal

### ISSUE THREAD

**Issue by dermorz** [berend/pyiban#3]
I think `get_account_number()`, `get_bank_code()` and `get_iban()` are bad names and don't really reflect what those methods are doing. In my opinion the API would be much clearer with those names:

`extract_account_number()`
`extract_bank_code()`
`generate_iban()`

What do you think?

**Comment by berend** [comment]
Naming things is hard - and your proposal sounds good! Will do tonight

**Comment by dermorz** [comment]
What about instead of 2 methods to extract account number and bank code, just create one method:

`split_iban()` which returns a tuple or named tuple of all components that can be extracted? For example `(country, account_number, bank_code)`? I mean the account number alone is not doing anything, the bank code without the country might be ambiguous… so if I need 2 things extracted, that's 2 calls on the same iban.
